[base]
mode = "workspace"
smart_pull = true

[mode.repository]
name = ""
build_on_update = false

[mode.repository.signing]
enabled = false
key = ""
on_gen = false

[mode.workspace]

[repositories]
name = [
	"1::amethyst",
	"1::malachite@development!",
	"2::notop-git",
	"3::appendage",
]
urls = [
	"https://github.com/crystal-linux/%repo%",
	"https://aur.archlinux.org/%repo%",
	"https://github.com/not-my-segfault/%repo%"
]