[base]
mode = "workspace"
smart_pull = true

[mode.workspace]
git_info = true
colorblind = false

[repositories]
repos = [
	"crs:amethyst",
	"crs:malachite/development!",
	"aur:notop-git",
	"nms:appendage",
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
aur = "https://aur.archlinux.org/{}"
nms = "https://github.com/not-my-segfault/{}"
