[base]
mode = "workspace"
smart_pull = true

[mode.repository]
name = ""
build_on_update = false

[mode.repository.signing]
enabled = false
key = ""
on_gen = false

[mode.workspace]

[repositories]
name = [
	"crs:amethyst",
	"crs:malachite/development!",
	"aur::notop-git",
	"nms::appendage",
]

[repositories.urls]
crs = "https://github.com/crystal-linux/%repo%"
aur = "https://aur.archlinux.org/%repo%"
nms = "https://github.com/not-my-segfault/%repo%"
