[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "repository-test"
build_on_update = true

[mode.repository.signing]
enabled = true
key = "michal@tar.black"
on_gen = true

[repositories]
repos = [
	"crs:malachite/development:0a5bdc9",
	"mic:apod:v.1.1.2",
	"pkg:pfetch!",
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
mic = "https://git.tar.black/michal/{}"
